# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install + Setup PNPM
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5
        run_install: true
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm run build --if-present
    - run: node main.js
      env:
        #Discord required variables
        DISCORD_COMMAND_PREFIX: ${{ secrets.DISCORD_COMMAND_PREFIX }}
        DISCORD_AUTH_TOKEN: ${{ secrets.DISCORD_AUTH_TOKEN }}
        #Github Build Variables
        DISCORD_BUILD_CHANNEL: ${{ secrets.DISCORD_BUILD_CHANNEL }}
        CURRENT_ENVIRONMENT: BUILD
